<?php

return [
    'riwayat_terdahulu' => [
        'darah_tinggi' => 'Darah tinggi',
        'penyakit_paru' => 'Penyakit paru (Asma, TBC dll)',
        'asam_lambung' => 'Asam lambung',
        'alergi' => 'Alergi',
        'riwayat_operasi' => 'Riwayat operasi',
        'riwayat_kecelakaan' => 'Riwayat kecelakaan',
        'riwayat_rawat_rs' => 'Riwayat rawat RS',
        'hepatitis' => 'Hepatitis',
        'kencing_manis' => 'Kencing manis',
        'patah_tulang' => 'Patah tulang (terpasang PEN)',
    ],

    'riwayat_keluarga' => [
        'kencing_manis' => 'Kencing manis',
        'darah_tinggi' => 'Darah tinggi',
        'asam_lambung' => 'Asam lambung',
        'alergi' => 'Alergi',
        'penyakit_paru' => 'Penyakit paru (Asma, TBC dll)',
        'stroke' => 'Stroke',
        'ginjal' => 'Ginjal',
        'hemorrhoid' => 'Hemorrhoid',
        'kanker' => 'Kanker',
        'jantung' => 'Jantung',
    ],

    'pajanan' => [
        'fisik' => [
            'kebisingan' => 'Kebisingan',
            'suhu_panas' => 'Suhu panas',
            'suhu_dingin' => 'Suhu dingin',
            'radiasi_non_pengion' => 'Radiasi bukan pengion (gel mikro, infrared, medan listrik)',
            'radiasi_pengion' => 'Radiasi pengion (sinar X, gamma)',
            'getaran_lokal' => 'Getaran lokal',
            'getaran_tubuh' => 'Getaran seluruh tubuh',
            'ketinggian' => 'Ketinggian',
        ],
        'kimia' => [
            'debu_anorganik' => 'Debu anorganik (silika, semen)',
            'debu_organik' => 'Debu organik (kapas, tekstil, gandum)',
            'asap' => 'Asap',
            'bahan_kimia' => 'Bahan kimia berbahaya',
            'logam_berat' => 'Logam berat (timah hitam, air raksa)',
            'pelarut_organik' => 'Pelarut organik (benzene, toluene)',
            'pestisida' => 'Pestisida',
        ],
        'biologi' => [
            'bakteri' => 'Bakteri / virus / jamur / parasit',
            'darah_cairan' => 'Darah / cairan tubuh lain',
            'nyamuk_serangga' => 'Nyamuk / serangga',
            'limbah' => 'Limbah (kotoran manusia / hewan)',
        ],
        'psikologis' => [
            'beban_kerja' => 'Beban kerja tidak sesuai waktu & jumlah',
            'kesesuaian_pekerjaan' => 'Pekerjaan tidak sesuai pengetahuan / keterampilan',
            'ketidakjelasan_tugas' => 'Ketidakjelasan tugas',
            'hambatan_karir' => 'Hambatan jenjang karir',
            'shift' => 'Bekerja giliran (shift)',
            'konflik_kerja' => 'Konflik dengan teman sekerja',
            'konflik_keluarga' => 'Konflik dalam keluarga',
        ],
        'ergonomis' => [
            'gerakan_berulang' => 'Gerakan berulang dengan tangan',
            'angkat_berat' => 'Angkat / angkut berat',
            'duduk_lama' => 'Duduk lama > 4 jam terus menerus',
            'berdiri_lama' => 'Berdiri lama > 4 jam terus menerus',
            'posisi_tidak_ergonomis' => 'Posisi tubuh tidak ergonomis',
            'pencahayaan' => 'Pencahayaan tidak sesuai',
            'layar_monitor' => 'Bekerja dengan layar / monitor 4 jam+ / hari',
        ],
    ],

    'fisik' => [
        'mata' => [
            'berkaca_mata' => 'Berkaca mata',
            'visus_kiri' => 'Visus Os (kiri)',
            'visus_kanan' => 'Visus Os (kanan)',
            'buta_warna' => 'Buta warna',
            'penyakit_mata' => 'Penyakit mata',
            'konjungtiva' => 'Konjungtiva',
            'sklera' => 'Sklera',
        ],
        'tht' => [
            'membran_tymp_kiri' => 'Membran timpani kiri',
            'membran_tymp_kanan' => 'Membran timpani kanan',
            'penyakit_telinga_kiri' => 'Penyakit telinga kiri',
            'penyakit_telinga_kanan' => 'Penyakit telinga kanan',
            'pilek_tersumbat' => 'Pilek / tersumbat',
            'lidah' => 'Lidah',
            'hidung_lain' => 'Hidung lain-lain',
            'tonsil_kanan' => 'Tonsil kanan',
            'tonsil_kiri' => 'Tonsil kiri',
            'pharing' => 'Pharing',
            'tiroid' => 'Tiroid',
            'kerongkongan_lain' => 'Kerongkongan lain-lain',
        ],
        'dada' => [
            'batas_jantung' => 'Batas-batas jantung',
            'iktus_kordis' => 'Iktus kordis',
            'paru_inspeksi_kanan' => 'Paru inspeksi kanan',
            'paru_inspeksi_kiri' => 'Paru inspeksi kiri',
            'paru_palpasi_kanan' => 'Paru palpasi kanan',
            'paru_palpasi_kiri' => 'Paru palpasi kiri',
            'paru_perkusi_kanan' => 'Paru perkusi kanan',
            'paru_perkusi_kiri' => 'Paru perkusi kiri',
            'paru_auskultasi_kanan' => 'Paru auskultasi kanan',
            'paru_auskultasi_kiri' => 'Paru auskultasi kiri',
        ],
        'perut' => [
            'inspeksi' => 'Inspeksi',
            'perkusi' => 'Perkusi',
            'auskultasi' => 'Auskultasi',
            'hati' => 'Hati',
            'limpa' => 'Limpa',
            'ginjal_kiri' => 'Ginjal kiri',
            'ginjal_kanan' => 'Ginjal kanan',
            'hernia' => 'Hernia',
            'tumor' => 'Tumor',
            'lain' => 'Lain-lain',
        ],
        'genitalia' => [
            'hernia' => 'Hernia',
            'haemorhoid' => 'Haemorhoid',
            'sikatriks' => 'Sikatriks',
            'spincter' => 'Spincter',
            'testis_prostat' => 'Epididimis / testis / prostat',
            'ekskresi' => 'Ekskresi',
        ],
        'gerak' => [
            'atas_kanan' => 'Anggota gerak atas kanan',
            'atas_kiri' => 'Anggota gerak atas kiri',
            'bawah_kanan' => 'Anggota gerak bawah kanan',
            'bawah_kiri' => 'Anggota gerak bawah kiri',
            'oedem_kanan' => 'Sembab / oedem kanan',
            'oedem_kiri' => 'Sembab / oedem kiri',
            'cacat_kanan' => 'Cacat kanan',
            'cacat_kiri' => 'Cacat kiri',
        ],
        'refleks' => [
            'pupil' => 'Pupil',
            'biceps_kanan' => 'Biceps kanan',
            'biceps_kiri' => 'Biceps kiri',
            'patella' => 'Patella',
            'triceps_kanan' => 'Triceps kanan',
            'triceps_kiri' => 'Triceps kiri',
            'achiles' => 'Achiles',
            'babinsky_kanan' => 'Babinsky kanan',
            'babinsky_kiri' => 'Babinsky kiri',
        ],
        'kelenjar' => [
            'cervical_kanan' => 'Cervical kanan',
            'cervical_kiri' => 'Cervical kiri',
            'axila_kanan' => 'Axila kanan',
            'axila_kiri' => 'Axila kiri',
            'supra_kanan' => 'Supra clavicula kanan',
            'supra_kiri' => 'Supra clavicula kiri',
            'infra_kanan' => 'Infra clavicula kanan',
            'infra_kiri' => 'Infra clavicula kiri',
            'inguinal_kanan' => 'Inguinal kanan',
            'inguinal_kiri' => 'Inguinal kiri',
        ],
    ],

    'fisik_text' => ['visus_kiri', 'visus_kanan'],
    'fisik_yn' => ['berkaca_mata', 'buta_warna', 'penyakit_mata', 'pilek_tersumbat'],

    'lab_groups' => [
        'hematologi' => [
            'hemoglobin' => ['label' => 'Hemoglobin', 'unit' => 'g/dl', 'ref' => '13.0 - 18.0', 'min' => 13, 'max' => 18],
            'hematokrit' => ['label' => 'Hematokrit', 'unit' => '%', 'ref' => '37.0 - 47.0', 'min' => 37, 'max' => 47],
            'eritrosit' => ['label' => 'Eritrosit', 'unit' => '10^6/mm3', 'ref' => '4.5 - 6.5', 'min' => 4.5, 'max' => 6.5],
            'trombosit' => ['label' => 'Trombosit', 'unit' => '10^3/mm3', 'ref' => '150 - 450', 'min' => 150, 'max' => 450],
            'leukosit' => ['label' => 'Leukosit', 'unit' => '10^3/mm3', 'ref' => '4.0 - 11.0', 'min' => 4, 'max' => 11],
            'mcv' => ['label' => 'MCV', 'unit' => 'fL', 'ref' => '79 - 99', 'min' => 79, 'max' => 99],
            'mch' => ['label' => 'MCH', 'unit' => 'pg', 'ref' => '27.0 - 31.0', 'min' => 27, 'max' => 31],
            'mchc' => ['label' => 'MCHC', 'unit' => '%', 'ref' => '33 - 37', 'min' => 33, 'max' => 37],
            'rdw' => ['label' => 'RDW', 'unit' => '%', 'ref' => '11.5 - 14.5', 'min' => 11.5, 'max' => 14.5],
            'led' => ['label' => 'LED', 'unit' => 'mm/jam', 'ref' => '0 - 20', 'min' => 0, 'max' => 20],
        ],
        'hitung_jenis' => [
            'limfosit' => ['label' => 'Limfosit', 'unit' => '%', 'ref' => '19 - 48', 'min' => 19, 'max' => 48],
            'granulosit' => ['label' => 'Granulosit', 'unit' => '10^3/mm3', 'ref' => '2.0 - 8.0', 'min' => 2, 'max' => 8],
            'mid' => ['label' => 'MID', 'unit' => '%', 'ref' => '2.0 - 15.0', 'min' => 2, 'max' => 15],
        ],
        'fungsi_hati' => [
            'bilirubin_total' => ['label' => 'Bilirubin Total', 'unit' => 'mg/dl', 'ref' => '< 1.00', 'min' => 0, 'max' => 1],
            'bilirubin_direct' => ['label' => 'Bilirubin Direct', 'unit' => 'mg/dl', 'ref' => '< 0.5', 'min' => 0, 'max' => 0.5],
            'sgot' => ['label' => 'SGOT / AST', 'unit' => 'U/L', 'ref' => '0 - 37', 'min' => 0, 'max' => 37],
            'sgpt' => ['label' => 'SGPT / ALT', 'unit' => 'U/L', 'ref' => '0 - 42', 'min' => 0, 'max' => 42],
        ],
        'fungsi_ginjal' => [
            'ureum' => ['label' => 'Ureum', 'unit' => 'mg/dl', 'ref' => '10.0 - 50.0', 'min' => 10, 'max' => 50],
            'creatinine' => ['label' => 'Creatinine', 'unit' => 'mg/dl', 'ref' => '0.6 - 1.1', 'min' => 0.6, 'max' => 1.1],
            'uric_acid' => ['label' => 'Uric Acid', 'unit' => 'mg/dl', 'ref' => '3.4 - 7.0', 'min' => 3.4, 'max' => 7],
        ],
        'karbohidrat' => [
            'glukosa_puasa' => ['label' => 'Glukosa Puasa', 'unit' => 'mg/dl', 'ref' => '70 - 100', 'min' => 70, 'max' => 100],
            'kgd_2jam' => ['label' => 'KGD 2 Jam PP', 'unit' => 'mg/dl', 'ref' => '< 180', 'min' => 0, 'max' => 180],
        ],
        'lipid' => [
            'cholesterol_total' => ['label' => 'Cholesterol Total', 'unit' => 'mg/dl', 'ref' => '<= 190', 'min' => 0, 'max' => 190],
            'hdl' => ['label' => 'HDL-Cholesterol', 'unit' => 'mg/dl', 'ref' => '> 40', 'min' => 40, 'max' => 100],
            'ldl' => ['label' => 'LDL-Cholesterol', 'unit' => 'mg/dl', 'ref' => '< 160', 'min' => 0, 'max' => 160],
            'trigliserida' => ['label' => 'Trigliserida', 'unit' => 'mg/dl', 'ref' => '< 150', 'min' => 0, 'max' => 150],
        ],
        'urinalisis' => [
            'leukosit_urin' => ['label' => 'Leukosit', 'unit' => '/ul', 'ref' => 'Negatif', 'min' => null, 'max' => null],
            'nitrit' => ['label' => 'Nitrit', 'unit' => '', 'ref' => 'Negatif', 'min' => null, 'max' => null],
            'urobilin' => ['label' => 'Urobilin', 'unit' => 'umol/l', 'ref' => '3.2 - 16', 'min' => 3.2, 'max' => 16],
            'protein' => ['label' => 'Protein', 'unit' => 'g/l', 'ref' => 'Negatif', 'min' => null, 'max' => null],
            'ph' => ['label' => 'pH', 'unit' => '', 'ref' => '4.5 - 8.0', 'min' => 4.5, 'max' => 8],
            'darah' => ['label' => 'Darah', 'unit' => '/ul', 'ref' => 'Negatif', 'min' => null, 'max' => null],
            'berat_jenis' => ['label' => 'Berat Jenis', 'unit' => '', 'ref' => '1.003 - 1.035', 'min' => 1.003, 'max' => 1.035],
            'keton' => ['label' => 'Keton', 'unit' => 'mg/dl', 'ref' => 'Negatif', 'min' => null, 'max' => null],
            'bilirubin_urin' => ['label' => 'Bilirubin', 'unit' => 'mg/dl', 'ref' => 'Negatif', 'min' => null, 'max' => null],
            'glukosa_urin' => ['label' => 'Glukosa', 'unit' => 'mg/dl', 'ref' => 'Negatif', 'min' => null, 'max' => null],
        ],
    ],

    'work_fitness_options' => [
        'Laik Bekerja Sesuai Posisi dan Lokasi Saat Ini',
        'Laik Bekerja Sesuai Posisi dan Lokasi Saat Ini, Dengan Catatan',
        'Laik Bekerja Dengan Penyesuaian dan atau Pembatasan Pekerjaan',
        'Tidak Laik Untuk Bekerja',
    ],

    'health_degrees' => [
        'P1' => 'P1. Tidak ditemukan kelainan medis',
        'P2' => 'P2. Tidak ditemukan kelainan medis yang tidak serius',
        'P3' => 'P3. Tidak ditemukan kelainan medis, resiko kesehatan rendah',
        'P4' => 'P4. Tidak ditemukan kelainan medis bermakna yang dapat menjadi serius, resiko kesehatan sedang',
        'P5' => 'P5. Tidak ditemukan kelainan medis yang serius, resiko kesehatan tinggi',
        'P6' => 'P6. Tidak ditemukan kelainan medis yang menyebabkan keterbatasan fisik maupun psikis untuk melakukan sesuai jabatan/posisinya',
        'P7' => 'P7. Tidak dapat bekerja untuk melakukan pekerjaan sesuai jabatan/posisinya dan/atau posisi apapun, dalam perawatan rumah sakit, atau dalam status ijin sakit',
    ],
];